// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./global.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SeoConfigProvider } from "../context/SeoConfigContext";
import SeoMeta from "../components/SeoMeta";
import DynamicScripts from "../components/DynamicScripts";
// import DynamicHeader from '../components/DynamicHeader';
// import DynamicFooter from '../components/DynamicFooter';

const inter = Inter({ subsets: ["latin"] });

// Default metadata (can be overridden by dynamic SEO config)


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SeoConfigProvider>
          {/* SEO & tracking setup */}
          <SeoMeta />
          <DynamicScripts />

          {/* Dynamic branding header */}
          {/* <DynamicHeader /> */}

          {/* Your existing app content */}
          <main>{children}</main>

          {/* Dynamic branding footer */}
          {/* <DynamicFooter /> */}
        </SeoConfigProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import { SeoConfigProvider } from '../context/SeoConfigContext';
// import DynamicScripts from '../components/DynamicScripts';
// // import DynamicHeader from '../components/DynamicHeader';
// // import DynamicFooter from '../components/DynamicFooter';

// const inter = Inter({ subsets: ['latin'] });

// // Server function to fetch SEO config
// async function getSeoConfig() {
//   try {
//     // In production, you can get the domain from headers
//     const domain =  'theartemis.ai';

//     const response = await fetch(
//       `/api/v1/seo-websites/domain/${domain}`,
//       {
//         headers: { "X-Tenant": "68b20dd0fb42964f2328b424" },
//         next: { revalidate: 3600 } // Cache for 1 hour
//       }
//     );

//     if (response.ok) {
//       return await response.json();
//     }
//     return null;
//   } catch (error) {
//     console.error("Error fetching SEO configuration:", error);
//     return null;
//   }
// }

// // Generate metadata dynamically
// export async function generateMetadata(): Promise<Metadata> {
//   const seoConfig = await getSeoConfig();

//   if (!seoConfig) {
//     return {
//       title: 'Default Title',
//       description: 'Default description',
//     };
//   }

//   const { seoConfig: config } = seoConfig;

//   return {
//     title: config.metaTitle,
//     description: config.metaDescription,
//     keywords: config.metaKeywords?.join(', '),
//     openGraph: {
//       title: config.metaTitle,
//       description: config.metaDescription,
//       images: [config.ogImage],
//       url: config.canonicalUrl,
//       type: 'website',
//     },
//     twitter: {
//       card: config.twitterCard,
//       title: config.metaTitle,
//       description: config.metaDescription,
//       images: [config.ogImage],
//     },
//     icons: {
//       icon: config.favicon,
//     },
//     alternates: {
//       canonical: config.canonicalUrl,
//     },
//   };
// }

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const seoConfig = await getSeoConfig();

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SeoConfigProvider initialConfig={seoConfig}>
//           <DynamicScripts />
//           {/* <DynamicHeader /> */}
//           <main>{children}</main>
//           {/* <DynamicFooter /> */}
//         </SeoConfigProvider>
//       </body>
//     </html>
//   );
// }

